# Generated by Django 2.2.7 on 2019-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachement',
            field=models.FileField(null=True, upload_to='contact/'),
        ),
    ]
